### ISSUE TITLE
android_native_app_glue.h: No such file or directory error

### ISSUE THREAD

**Issue by radman-x** [borisvanschooten/glesjs#11]
First of all, thank you for this great project. With a little more work, this could be a killer project and a great complement to Ejecta.

We have found several bugs we would like to debug. However, when building this project straight from the repo, we get the following error:

   main.cpp "android_native_app_glue.h: No such file or directory"

This is the same error mentioned in this post:

 [http://www.html5gamedevs.com/topic/7501-wip-glesjs-opengl-es-bindings-for-js-aka-fast-webgl-for-android/?do=findComment&comment=123482](url)

We probably will need this to rebuild libgles.js to fix the audio bug described here:

[http://www.html5gamedevs.com/topic/7501-wip-glesjs-opengl-es-bindings-for-js-aka-fast-webgl-for-android/?do=findComment&comment=124938](url)

(And also to implement video element which we need).

Please give some suggestions how to get build working.

Note: we can successfully build Bdr76's project from here but it has no audio (nor video, of course):

[https://github.com/BdR76/GLES.JS-Android-Studio-project](url)

**Comment by borisvanschooten** [comment]
Problem should be fixed now.
